# Generated by Django 4.1.3 on 2023-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_category_desc_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
